//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPS.HiltonDirect.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class EchannelRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EchannelRequest()
        {
            this.Requests = new HashSet<Request>();
        }
    
        public int Id { get; set; }
        public string SPRId { get; set; }
        public string Admin1Id { get; set; }
        public string Admin2Id { get; set; }
        public string Admin3Id { get; set; }
        public string Admin4Id { get; set; }
        public string Admin5Id { get; set; }
        public Nullable<System.DateTimeOffset> DecisionDueDate { get; set; }
        public Nullable<int> FollowUpActivityId { get; set; }
        public Nullable<bool> IsCommissionable { get; set; }
        public Nullable<double> CommissionRate { get; set; }
        public Nullable<bool> IsCreateTask { get; set; }
        public Nullable<System.DateTimeOffset> TaskDueDate { get; set; }
        public Nullable<int> MeetingClassId { get; set; }
    
        public virtual Person Admin1 { get; set; }
        public virtual Person Admin2 { get; set; }
        public virtual Person Admin3 { get; set; }
        public virtual Person Admin4 { get; set; }
        public virtual Person Admin5 { get; set; }
        public virtual FollowUpActivity FollowUpActivity { get; set; }
        public virtual MeetingClass MeetingClass { get; set; }
        public virtual Person SPRPerson { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request> Requests { get; set; }
    }
}
