CREATE TABLE [hd].[EchannelRequests]
(
	[Id] INT NOT NULL IDENTITY(1,1),
	[SPRId] VARCHAR(100) NULL, 
    [Admin1Id] VARCHAR(100) NULL, 
    [Admin2Id] VARCHAR(100) NULL, 
    [Admin3Id] VARCHAR(100) NULL, 
    [Admin4Id] VARCHAR(100) NULL, 
    [Admin5Id] VARCHAR(100) NULL, 
    [DecisionDueDate] DATETIMEOFFSET NULL, 
    [FollowUpActivityId] INT NULL, 
    [IsCommissionable] BIT NULL, 
    [CommissionRate] FLOAT NULL, 
    [IsCreateTask] BIT NULL, 
    [TaskDueDate] DATETIMEOFFSET NULL, 
    [MeetingClassId] INT NULL, 
    CONSTRAINT [PK_EchannelRequests] PRIMARY KEY CLUSTERED ([Id] ASC),
	CONSTRAINT [FK_EchannelRequests_SPRPersons] FOREIGN KEY ([SPRId]) REFERENCES [hd].[Persons] ([EmailAddress]),
	CONSTRAINT [FK_EchannelRequests_Admin1] FOREIGN KEY ([Admin1Id]) REFERENCES [hd].[Persons] ([EmailAddress]),
	CONSTRAINT [FK_EchannelRequests_Admin2] FOREIGN KEY ([Admin2Id]) REFERENCES [hd].[Persons] ([EmailAddress]),
	CONSTRAINT [FK_EchannelRequests_Admin3] FOREIGN KEY ([Admin3Id]) REFERENCES [hd].[Persons] ([EmailAddress]),
	CONSTRAINT [FK_EchannelRequests_Admin4] FOREIGN KEY ([Admin4Id]) REFERENCES [hd].[Persons] ([EmailAddress]),
	CONSTRAINT [FK_EchannelRequests_Admin5] FOREIGN KEY ([Admin5Id]) REFERENCES [hd].[Persons] ([EmailAddress]),
	CONSTRAINT [FK_EchannelRequests_FollowUpActivities] FOREIGN KEY ([FollowUpActivityId]) REFERENCES [hd].[FollowUpActivities] ([Id]),
	CONSTRAINT [FK_EchannelRequests_MeetingClasses] FOREIGN KEY ([MeetingClassId]) REFERENCES [hd].[MeetingClasses] ([Id]),
)
