//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPS.HiltonDirect.Model {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BPS.HiltonDirect.Model.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied..
        /// </summary>
        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin #1.
        /// </summary>
        public static string admin1 {
            get {
                return ResourceManager.GetString("admin1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin #2.
        /// </summary>
        public static string admin2 {
            get {
                return ResourceManager.GetString("admin2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin #3.
        /// </summary>
        public static string admin3 {
            get {
                return ResourceManager.GetString("admin3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin #4.
        /// </summary>
        public static string admin4 {
            get {
                return ResourceManager.GetString("admin4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin #5.
        /// </summary>
        public static string admin5 {
            get {
                return ResourceManager.GetString("admin5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API.
        /// </summary>
        public static string API {
            get {
                return ResourceManager.GetString("API", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string browse_filter {
            get {
                return ResourceManager.GetString("browse_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string clear {
            get {
                return ResourceManager.GetString("clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create request.
        /// </summary>
        public static string create_request {
            get {
                return ResourceManager.GetString("create_request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot remove this item. Please remove all of references..
        /// </summary>
        public static string delete_error {
            get {
                return ResourceManager.GetString("delete_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string dialog_confirm {
            get {
                return ResourceManager.GetString("dialog_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string dialog_error {
            get {
                return ResourceManager.GetString("dialog_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infomation.
        /// </summary>
        public static string dialog_info {
            get {
                return ResourceManager.GetString("dialog_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string dialog_warning {
            get {
                return ResourceManager.GetString("dialog_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decision Due.
        /// </summary>
        public static string due_date {
            get {
                return ResourceManager.GetString("due_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit request.
        /// </summary>
        public static string edit_request {
            get {
                return ResourceManager.GetString("edit_request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following fields have invalid or missing input:.
        /// </summary>
        public static string fields_missing_error {
            get {
                return ResourceManager.GetString("fields_missing_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form is invalid. Please verify data filled out in the form..
        /// </summary>
        public static string form_invalid {
            get {
                return ResourceManager.GetString("form_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more dates in the form has an invalid format. Please ensure all dates use the ddMMMyyyy format..
        /// </summary>
        public static string form_invalid_date_format_msg {
            get {
                return ResourceManager.GetString("form_invalid_date_format_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is this an eChannel, Inbound, or NSO form ?.
        /// </summary>
        public static string form_option {
            get {
                return ResourceManager.GetString("form_option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get data error..
        /// </summary>
        public static string GetDataError {
            get {
                return ResourceManager.GetString("GetDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hilton Sales Echannel Request Form.
        /// </summary>
        public static string hilton_direct_form_title {
            get {
                return ResourceManager.GetString("hilton_direct_form_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string id {
            get {
                return ResourceManager.GetString("id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid date format. Please use the ddMMMyyyy format..
        /// </summary>
        public static string invalid_date_format_msg {
            get {
                return ResourceManager.GetString("invalid_date_format_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to list.
        /// </summary>
        public static string list_view {
            get {
                return ResourceManager.GetString("list_view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No item found.
        /// </summary>
        public static string no_items_found {
            get {
                return ResourceManager.GetString("no_items_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove request.
        /// </summary>
        public static string remove_request {
            get {
                return ResourceManager.GetString("remove_request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repositories.
        /// </summary>
        public static string Repositories {
            get {
                return ResourceManager.GetString("Repositories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this request?.
        /// </summary>
        public static string request_delete_confirmation {
            get {
                return ResourceManager.GetString("request_delete_confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Rep Note.
        /// </summary>
        public static string sales_rep_note {
            get {
                return ResourceManager.GetString("sales_rep_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPR.
        /// </summary>
        public static string spr {
            get {
                return ResourceManager.GetString("spr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property: {0} Error: {1}.
        /// </summary>
        public static string TraceInfo {
            get {
                return ResourceManager.GetString("TraceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait.
        /// </summary>
        public static string waiting_text {
            get {
                return ResourceManager.GetString("waiting_text", resourceCulture);
            }
        }
    }
}
